<?xml version="1.0"?>
<ModelInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <RotationX>0</RotationX>
  <RotationY>0</RotationY>
  <RotationZ>0</RotationZ>
  <PositionX>0</PositionX>
  <PositionY>0</PositionY>
  <PositionZ>0</PositionZ>
  <Scale>0.15</Scale>
  <Models>
    <Keys>
      <int>0</int>
    </Keys>
    <Values>
      <LODModelInfo>
        <CollisionModelFilepath>NULL</CollisionModelFilepath>
        <ModelFilepath>Models/Sphere2/Sphere</ModelFilepath>
        <Shaders>
          <Keys>
            <string>Sphere</string>
          </Keys>
          <Values>
            <Shader xsi:type="BasicMaterial">
              <TextureFilepath>Models/Sphere2/UV_0</TextureFilepath>
              <NormalMapFilepath>Models/Sphere2/Norm</NormalMapFilepath>
            </Shader>
          </Values>
        </Shaders>
      </LODModelInfo>
    </Values>
  </Models>
</ModelInfo>